server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: gateway-api 
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*" #mozda obrisati?
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

        - id: load-balancer-servis
          uri: http://load-balancer-servis
          predicates:
            - Path=/load-balancer-servis/**
        - id: orderModules
          uri: http://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - AuthFilter
        - id: recommendationModules
          uri: http://recommendation-service
          predicates:
            - Path=/recommendation-service/**
          filters:
            - AuthFilter
        - id: restaurantModules
          uri: http://restaurant-service
          predicates:
            - Path=/restaurants/**
          filters:
            - AuthFilter
            
        - id: userModules
          uri: http://users-service
          predicates:
            - Path=/users-service/**