server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: userModules
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: load-balancer-servis
          uri: http://load-balancer-servis
          predicates:
            - Path=/load-balancer-servis/**
        - id: orderModules
          uri: http://order-service
          predicates:
            - Path=/order-service/**
        - id: recommendationModules
          uri: http://recommendation-service
          predicates:
            - Path=/recommendation-service/**
        - id: authModules
          uri: http://auth-service
          predicates:
            - Path=/auth-service/**